# fly.toml app configuration file generated for relayfx on 2026-08-21T23:26:55Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'relayfx'
primary_region = 'cdg'

[http_service]
  auto_start_machines = true
  auto_stop_machines = 'stop'
  force_https = true
  internal_port = 1000
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '1gb'
  memory_mb = 256
